development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: v16_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: v16_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
